version: '3'

services:
  postgres:
    container_name: chess_ms_postgres
    image: "postgres:15.2-alpine"
    user: postgres
    environment:
      - POSTGRES_USER=chess_ms
      - POSTGRES_PASSWORD=chess_ms
      - POSTGRES_DB=chess_ms
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/chess_ms
volumes:
  postgres_data:
    driver: local
