version: '3'

services:
  postgres:
    container_name: users_ms_postgres
    image: "postgres:15.2-alpine"
    user: postgres
    environment:
      - POSTGRES_USER=users_ms
      - POSTGRES_PASSWORD=users_ms
      - POSTGRES_DB=users_ms
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
