type EnumDictionary<T extends string | symbol | number, U> = {
    [K in T]: U;
};

enum StatusCodeEnums {
    EMAIL_DUPLICATED = 10001,

    USER_NOT_FOUND = 10010,
    USER_ALREADY_EXISTS,
    PASSWORD_HAS_BEEN_CREATED_FOR_THIS_USER,
    USER_IS_ALREADY_ACTIVE,
    FAILED_TO_ADD_USER,
    USER_CREATEDBY_NO_EXISTS,

    ROLE_NAME_IS_REQUIRED = 10020,
    ROLE_ALREADY_EXISTS,
    ROLE_NOT_FOUND,
    ROLE_NOT_EXIST_IN_THE_ACCOUNT,

    PERMISSIONS_NOT_FOUND = 10030,

    CLIENT_NOT_FOUND = 10040,
    CLIENT_NAME_ALREADY_EXISTS,

    COMPANY_NOT_FOUND = 10050,
    COMPANY_NAME_ALREADY_EXISTS,
    COMPANIES_NOT_EXIST,

    CAMPAING_NOT_FOUND = 10060,
    CAMPAIGNS_NOT_EXIST,

    COUNTRY_NOT_FOUND = 10070,
    COUNTRY_ACRONYM_NOT_FOUND,

    CITY_NAME_ALREADY_EXISTS = 10080,
    CITY_NOT_FOUND,

    TEAM_NOT_FOUND = 10090,
    TEAM_NOT_BELONG_TO_THE_ACCOUNT,
    TEAM_ALREADY_EXISTS,
    TEAM_ALREADY_HAS_THIS_NAME,

    PHONE_NUMBER_ALREADY_EXISTS = 10100,

    INVALID_PASSWORD_USERNAME = 10110,

    INVALID_CITY_ACRONYM = 10120,

    AUDIO_NOT_FOUND = 10130,
    AUDIO_STATE_NOT_FOUND,
    AUDIO_IS_COMPLETED,
    AUDIO_IS_NOT_ACCEPTABLE_TO_CONFIRM_EVALUATION,

    LIMIT_QUERY = 10140,

    SUPERVISOR_ALREADY_EXISTS = 10150,

    EVALUATION_NOT_FOUND = 10160,
    EVALUATION_FOUND,
}

const StatusCodeExceptionText: EnumDictionary<StatusCodeEnums, string> = {
    [StatusCodeEnums.EMAIL_DUPLICATED]: 'EMAIL_DUPLICATED',
    [StatusCodeEnums.USER_NOT_FOUND]: 'USER_NOT_FOUND',
    [StatusCodeEnums.USER_ALREADY_EXISTS]: 'USER_ALREADY_EXISTS',
    [StatusCodeEnums.PASSWORD_HAS_BEEN_CREATED_FOR_THIS_USER]: 'PASSWORD_HAS_BEEN_CREATED_FOR_THIS_USER',
    [StatusCodeEnums.USER_IS_ALREADY_ACTIVE]: 'USER_IS_ALREADY_ACTIVE',
    [StatusCodeEnums.FAILED_TO_ADD_USER]: 'FAILED_TO_ADD_USER',
    [StatusCodeEnums.ROLE_NAME_IS_REQUIRED]: 'ROLE_NAME_IS_REQUIRED',
    [StatusCodeEnums.ROLE_ALREADY_EXISTS]: 'ROLE_ALREADY_EXISTS',
    [StatusCodeEnums.ROLE_NOT_FOUND]: 'ROLE_NOT_FOUND',
    [StatusCodeEnums.ROLE_NOT_EXIST_IN_THE_ACCOUNT]: 'ROLE_NOT_EXIST_IN_THE_ACCOUNT',
    [StatusCodeEnums.PERMISSIONS_NOT_FOUND]: 'PERMISSIONS_NOT_FOUND',
    [StatusCodeEnums.CLIENT_NOT_FOUND]: 'CLIENT_NOT_FOUND',
    [StatusCodeEnums.CLIENT_NAME_ALREADY_EXISTS]: 'CLIENT_NAME_ALREADY_EXISTS',
    [StatusCodeEnums.COMPANY_NOT_FOUND]: 'COMPANY_NOT_FOUND',
    [StatusCodeEnums.COMPANY_NAME_ALREADY_EXISTS]: 'COMPANY_NAME_ALREADY_EXISTS',
    [StatusCodeEnums.COMPANIES_NOT_EXIST]: 'COMPANIES_NOT_EXIST',
    [StatusCodeEnums.CAMPAING_NOT_FOUND]: 'CAMPAING_NOT_FOUND',
    [StatusCodeEnums.CAMPAIGNS_NOT_EXIST]: 'CAMPAIGNS_NOT_EXIST',
    [StatusCodeEnums.COUNTRY_NOT_FOUND]: 'COUNTRY_NOT_FOUND',
    [StatusCodeEnums.COUNTRY_ACRONYM_NOT_FOUND]: 'COUNTRY_ACRONYM_NOT_FOUND',
    [StatusCodeEnums.CITY_NAME_ALREADY_EXISTS]: 'CITY_NAME_ALREADY_EXISTS',
    [StatusCodeEnums.CITY_NOT_FOUND]: 'CITY_NOT_FOUND',
    [StatusCodeEnums.TEAM_NOT_FOUND]: 'TEAM_NOT_FOUND',
    [StatusCodeEnums.TEAM_NOT_BELONG_TO_THE_ACCOUNT]: 'TEAM_NOT_BELONG_TO_THE_ACCOUNT',
    [StatusCodeEnums.TEAM_ALREADY_EXISTS]: 'TEAM_ALREADY_EXISTS',
    [StatusCodeEnums.TEAM_ALREADY_HAS_THIS_NAME]: 'TEAM_ALREADY_HAS_THIS_NAME',
    [StatusCodeEnums.PHONE_NUMBER_ALREADY_EXISTS]: 'PHONE_NUMBER_ALREADY_EXISTS',
    [StatusCodeEnums.INVALID_PASSWORD_USERNAME]: 'INVALID_PASSWORD_USERNAME',
    [StatusCodeEnums.INVALID_CITY_ACRONYM]: 'INVALID_CITY_ACRONYM',
    [StatusCodeEnums.AUDIO_NOT_FOUND]: 'AUDIO_NOT_FOUND',
    [StatusCodeEnums.AUDIO_STATE_NOT_FOUND]: 'AUDIO_STATE_NOT_FOUND',
    [StatusCodeEnums.AUDIO_IS_COMPLETED]: 'AUDIO_IS_COMPLETED',
    [StatusCodeEnums.AUDIO_IS_NOT_ACCEPTABLE_TO_CONFIRM_EVALUATION]: 'AUDIO_IS_NOT_ACCEPTABLE_TO_CONFIRM_EVALUATION',
    [StatusCodeEnums.LIMIT_QUERY]: 'LIMIT_QUERY',
    [StatusCodeEnums.SUPERVISOR_ALREADY_EXISTS]: 'SUPERVISOR_ALREADY_EXISTS',
    [StatusCodeEnums.EVALUATION_NOT_FOUND]: 'EVALUATION_NOT_FOUND',
    [StatusCodeEnums.EVALUATION_FOUND]: 'EVALUATION_FOUND',
    [StatusCodeEnums.USER_CREATEDBY_NO_EXISTS]: 'USER_CREATEDBY_NO_EXISTS',
};

export { StatusCodeEnums, StatusCodeExceptionText };
